In [4]:
import pandas as pd
import json
from sqlalchemy import create_engine, text

In [3]:
listings_path = r"C:\Users\KUMAR\Downloads\listings_final_expanded.json"
attributes_path = r"C:\Users\KUMAR\Downloads\property_attributes_final_expanded.json"
agents_path = r"C:\Users\KUMAR\Downloads\agents_cleaned.json"
sales_path = r"C:\Users\KUMAR\Downloads\sales_cleaned.csv"
buyers_path = r"C:\Users\KUMAR\Downloads\buyers_cleaned.json"

In [5]:
listings_df = pd.read_json(listings_path)
attributes_df = pd.read_json(attributes_path)
agents_df = pd.read_json(agents_path)
sales_df = pd.read_csv(sales_path)
buyers_df = pd.read_json(buyers_path)

In [6]:
print("Listings shape:", listings_df.shape)
print("Attributes shape:", attributes_df.shape)
print("Agents shape:", agents_df.shape)
print("Sales shape:", sales_df.shape)
print("Buyers shape:", buyers_df.shape)

Listings shape: (21200, 9)
Attributes shape: (21200, 13)
Agents shape: (50, 9)
Sales shape: (720, 4)
Buyers shape: (20000, 7)

In [7]:
print("Listings")
print(listings_df.columns)
print(listings_df.dtypes)
print()

print("Attributes")
print(attributes_df.columns)
print(attributes_df.dtypes)
print()

print("Agents")
print(agents_df.columns)
print(agents_df.dtypes)
print()

print("Sales")
print(sales_df.columns)
print(sales_df.dtypes)
print()

print("Buyers")
print(buyers_df.columns)
print(buyers_df.dtypes)

Listings
Index(['Listing_ID', 'City', 'Property_Type', 'Price', 'Sqft', 'Date_Listed',
       'Agent_ID', 'Latitude', 'Longitude'],
      dtype='str')
Listing_ID           str
City                 str
Property_Type        str
Price            float64
Sqft             float64
Date_Listed          str
Agent_ID             str
Latitude         float64
Longitude        float64
dtype: object

Attributes
Index(['attribute_id', 'listing_id', 'bedrooms', 'bathrooms', 'floor_number',
       'total_floors', 'year_built', 'is_rented', 'tenant_count',
       'furnishing_status', 'metro_distance_km', 'parking_available',
       'power_backup'],
      dtype='str')
attribute_id           int64
listing_id               str
bedrooms               int64
bathrooms              int64
floor_number           int64
total_floors           int64
year_built             int64
is_rented               bool
tenant_count           int64
furnishing_status        str
metro_distance_km    float64
parking_available       bool
power_backup            bool
dtype: object

Agents
Index(['Agent_ID', 'Name', 'Phone', 'Email', 'commission_rate', 'deals_closed',
       'rating', 'experience_years', 'avg_closing_days'],
      dtype='str')
Agent_ID                str
Name                    str
Phone                   str
Email                   str
commission_rate     float64
deals_closed          int64
rating              float64
experience_years      int64
avg_closing_days      int64
dtype: object

Sales
Index(['Listing_ID', 'Sale_Price', 'Date_Sold', 'Days_on_Market'], dtype='str')
Listing_ID            str
Sale_Price        float64
Date_Sold             str
Days_on_Market    float64
dtype: object

Buyers
Index(['buyer_id', 'sale_id', 'buyer_type', 'payment_mode', 'loan_taken',
       'loan_provider', 'loan_amount'],
      dtype='str')
buyer_id         int64
sale_id            str
buyer_type         str
payment_mode       str
loan_taken        bool
loan_provider      str
loan_amount      int64
dtype: object

In [8]:
listings_df.head()

,Listing_ID,City,Property_Type,Price,Sqft,Date_Listed,Agent_ID,Latitude,Longitude
0,L00001,New York,Apartment,1.655144e+06,2753.009121,2023-05-06,A0015,33.965208,-69.861589
1,L00002,Los Angeles,Apartment,1.519141e+06,4966.988193,2023-02-14,A0038,42.547892,-90.277860
2,L00003,Houston,Apartment,1.624890e+05,1267.003959,2023-04-22,A0015,28.732327,-115.952982
3,L00004,Phoenix,Apartment,1.277016e+06,2128.014429,2024-01-02,A0042,26.403938,-74.771490
4,L00005,Phoenix,Townhouse,5.622970e+05,4178.997421,2023-10-29,A0018,39.425252,-83.917878

In [9]:
attributes_df.head()
agents_df.head()
sales_df.head()
buyers_df.head()

,buyer_id,sale_id,buyer_type,payment_mode,loan_taken,loan_provider,loan_amount
0,1,L01179,End User,Cash,False,NaN,0
1,2,L00866,Investor,Cheque,False,NaN,0
2,3,L00102,Investor,Cheque,True,Axis,2317757
3,4,L00440,Investor,Bank Transfer,False,NaN,0
4,5,L00059,Investor,UPI,True,HDFC,4191221

In [10]:
listings_df.columns = listings_df.columns.str.lower()
attributes_df.columns = attributes_df.columns.str.lower()
agents_df.columns = agents_df.columns.str.lower()
sales_df.columns = sales_df.columns.str.lower()
buyers_df.columns = buyers_df.columns.str.lower()

In [11]:
print(listings_df.columns)
print(attributes_df.columns)
print(agents_df.columns)
print(sales_df.columns)
print(buyers_df.columns)

Index(['listing_id', 'city', 'property_type', 'price', 'sqft', 'date_listed',
       'agent_id', 'latitude', 'longitude'],
      dtype='str')
Index(['attribute_id', 'listing_id', 'bedrooms', 'bathrooms', 'floor_number',
       'total_floors', 'year_built', 'is_rented', 'tenant_count',
       'furnishing_status', 'metro_distance_km', 'parking_available',
       'power_backup'],
      dtype='str')
Index(['agent_id', 'name', 'phone', 'email', 'commission_rate', 'deals_closed',
       'rating', 'experience_years', 'avg_closing_days'],
      dtype='str')
Index(['listing_id', 'sale_price', 'date_sold', 'days_on_market'], dtype='str')
Index(['buyer_id', 'sale_id', 'buyer_type', 'payment_mode', 'loan_taken',
       'loan_provider', 'loan_amount'],
      dtype='str')

In [12]:
listings_df["date_listed"] = pd.to_datetime(listings_df["date_listed"])
sales_df["date_sold"] = pd.to_datetime(sales_df["date_sold"])

In [13]:
print(listings_df.dtypes)
print(sales_df.dtypes)

listing_id                  str
city                        str
property_type               str
price                   float64
sqft                    float64
date_listed      datetime64[us]
agent_id                    str
latitude                float64
longitude               float64
dtype: object
listing_id                   str
sale_price               float64
date_sold         datetime64[us]
days_on_market           float64
dtype: object

In [14]:
print("Listings null values")
print(listings_df.isnull().sum())
print()

print("Attributes null values")
print(attributes_df.isnull().sum())
print()

print("Agents null values")
print(agents_df.isnull().sum())
print()

print("Sales null values")
print(sales_df.isnull().sum())
print()

print("Buyers null values")
print(buyers_df.isnull().sum())

Listings null values
listing_id       0
city             0
property_type    0
price            0
sqft             0
date_listed      0
agent_id         0
latitude         0
longitude        0
dtype: int64

Attributes null values
attribute_id         0
listing_id           0
bedrooms             0
bathrooms            0
floor_number         0
total_floors         0
year_built           0
is_rented            0
tenant_count         0
furnishing_status    0
metro_distance_km    0
parking_available    0
power_backup         0
dtype: int64

Agents null values
agent_id            0
name                0
phone               0
email               0
commission_rate     0
deals_closed        0
rating              0
experience_years    0
avg_closing_days    0
dtype: int64

Sales null values
listing_id        0
sale_price        0
date_sold         0
days_on_market    0
dtype: int64

Buyers null values
buyer_id            0
sale_id             0
buyer_type          0
payment_mode        0
loan_taken          0
loan_provider    9966
loan_amount         0
dtype: int64

In [15]:
print("Listings duplicates:", listings_df.duplicated().sum())
print("Attributes duplicates:", attributes_df.duplicated().sum())
print("Agents duplicates:", agents_df.duplicated().sum())
print("Sales duplicates:", sales_df.duplicated().sum())
print("Buyers duplicates:", buyers_df.duplicated().sum())

Listings duplicates: 0
Attributes duplicates: 0
Agents duplicates: 0
Sales duplicates: 0
Buyers duplicates: 0

In [16]:
print("Duplicate listing_id in listings:", listings_df["listing_id"].duplicated().sum())
print("Duplicate listing_id in attributes:", attributes_df["listing_id"].duplicated().sum())
print("Duplicate agent_id in agents:", agents_df["agent_id"].duplicated().sum())
print("Duplicate listing_id in sales:", sales_df["listing_id"].duplicated().sum())
print("Duplicate buyer_id in buyers:", buyers_df["buyer_id"].duplicated().sum())

Duplicate listing_id in listings: 0
Duplicate listing_id in attributes: 0
Duplicate agent_id in agents: 0
Duplicate listing_id in sales: 0
Duplicate buyer_id in buyers: 0

In [17]:
print("Listings count:", listings_df["listing_id"].nunique())
print("Attributes count:", attributes_df["listing_id"].nunique())
print("Sales count:", sales_df["listing_id"].nunique())
print("Agents count:", agents_df["agent_id"].nunique())
print("Buyers count:", buyers_df["buyer_id"].nunique())

Listings count: 21200
Attributes count: 21200
Sales count: 720
Agents count: 50
Buyers count: 20000

In [18]:
print("Attributes listing_id not in listings:",
      ~attributes_df["listing_id"].isin(listings_df["listing_id"]).sum())

Attributes listing_id not in listings: -21201

In [19]:
print("Attributes not matching listings:",
      (~attributes_df["listing_id"].isin(listings_df["listing_id"])).sum())

print("Sales not matching listings:",
      (~sales_df["listing_id"].isin(listings_df["listing_id"])).sum())

print("Listings with invalid agent_id:",
      (~listings_df["agent_id"].isin(agents_df["agent_id"])).sum())

print("Buyers not matching sales:",
      (~buyers_df["sale_id"].isin(sales_df["listing_id"])).sum())

Attributes not matching listings: 0
Sales not matching listings: 0
Listings with invalid agent_id: 0
Buyers not matching sales: 0

In [20]:
from sqlalchemy import create_engine, text

USER = "postgres"
PASSWORD = "258963"
HOST = "localhost"
PORT = "5432"
DB_NAME = "brickview"

DATABASE_URL = f"postgresql+psycopg2://{USER}:{PASSWORD}@{HOST}:{PORT}/{DB_NAME}"
engine = create_engine(DATABASE_URL)
print(engine)

Engine(postgresql+psycopg2://postgres:***@localhost:5432/brickview)

In [21]:
try:
    with engine.connect() as connection:
        result = connection.execute(text("SELECT current_database();"))
        print("Connection successful")
        print("Connected database:", result.fetchone()[0])
except Exception as e:
    print("Error connecting to the database")
    print(e)

Connection successful
Connected database: brickview

In [22]:
create_tables_query = """
CREATE TABLE IF NOT EXISTS agents (
    agent_id VARCHAR(10) PRIMARY KEY,
    name VARCHAR(100),
    phone VARCHAR(30),
    email VARCHAR(100),
    commission_rate NUMERIC(5,2),
    deals_closed INT,
    rating NUMERIC(3,2),
    experience_years INT,
    avg_closing_days INT
);

CREATE TABLE IF NOT EXISTS listings (
    listing_id VARCHAR(10) PRIMARY KEY,
    city VARCHAR(100),
    property_type VARCHAR(50),
    price NUMERIC(15,2),
    sqft NUMERIC(12,2),
    date_listed DATE,
    agent_id VARCHAR(10),
    latitude NUMERIC(10,6),
    longitude NUMERIC(10,6),
    CONSTRAINT fk_listings_agent
        FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
);

CREATE TABLE IF NOT EXISTS property_attributes (
    attribute_id INT PRIMARY KEY,
    listing_id VARCHAR(10) UNIQUE,
    bedrooms INT,
    bathrooms INT,
    floor_number INT,
    total_floors INT,
    year_built INT,
    is_rented BOOLEAN,
    tenant_count INT,
    furnishing_status VARCHAR(50),
    metro_distance_km NUMERIC(6,2),
    parking_available BOOLEAN,
    power_backup BOOLEAN,
    CONSTRAINT fk_attributes_listing
        FOREIGN KEY (listing_id) REFERENCES listings(listing_id)
);

CREATE TABLE IF NOT EXISTS sales (
    listing_id VARCHAR(10) PRIMARY KEY,
    sale_price NUMERIC(15,2),
    date_sold DATE,
    days_on_market NUMERIC(10,2),
    CONSTRAINT fk_sales_listing
        FOREIGN KEY (listing_id) REFERENCES listings(listing_id)
);

CREATE TABLE IF NOT EXISTS buyers (
    buyer_id INT PRIMARY KEY,
    sale_id VARCHAR(10),
    buyer_type VARCHAR(50),
    payment_mode VARCHAR(50),
    loan_taken BOOLEAN,
    loan_provider VARCHAR(100),
    loan_amount NUMERIC(15,2),
    CONSTRAINT fk_buyers_sale
        FOREIGN KEY (sale_id) REFERENCES sales(listing_id)
);
"""

In [23]:
with engine.connect() as connection:
    for query in create_tables_query.split(";"):
        if query.strip():
            connection.execute(text(query))
    connection.commit()

print("Tables created successfully")

Tables created successfully

In [24]:
check_tables = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';
"""

pd.read_sql(check_tables, engine)

            table_name
0               agents
1             listings
2  property_attributes
3                sales
4               buyers

In [25]:
print(listings_df.columns)
print(attributes_df.columns)
print(agents_df.columns)
print(sales_df.columns)
print(buyers_df.columns)

Index(['listing_id', 'city', 'property_type', 'price', 'sqft', 'date_listed',
       'agent_id', 'latitude', 'longitude'],
      dtype='str')
Index(['attribute_id', 'listing_id', 'bedrooms', 'bathrooms', 'floor_number',
       'total_floors', 'year_built', 'is_rented', 'tenant_count',
       'furnishing_status', 'metro_distance_km', 'parking_available',
       'power_backup'],
      dtype='str')
Index(['agent_id', 'name', 'phone', 'email', 'commission_rate', 'deals_closed',
       'rating', 'experience_years', 'avg_closing_days'],
      dtype='str')
Index(['listing_id', 'sale_price', 'date_sold', 'days_on_market'], dtype='str')
Index(['buyer_id', 'sale_id', 'buyer_type', 'payment_mode', 'loan_taken',
       'loan_provider', 'loan_amount'],
      dtype='str')

In [26]:
agents_df.to_sql("agents", engine, if_exists="append", index=False)
print("agents loaded")

agents loaded

In [27]:
listings_df.to_sql("listings", engine, if_exists="append", index=False)
print("listings loaded")

listings loaded

In [28]:
attributes_df.to_sql("property_attributes", engine, if_exists="append", index=False)
print("property_attributes loaded")

property_attributes loaded

In [29]:
sales_df.to_sql("sales", engine, if_exists="append", index=False)
print("sales loaded")

sales loaded

In [30]:
buyers_df.to_sql("buyers", engine, if_exists="append", index=False)
print("buyers loaded")

buyers loaded

In [31]:
print(pd.read_sql("SELECT COUNT(*) AS count FROM agents", engine))
print(pd.read_sql("SELECT COUNT(*) AS count FROM listings", engine))
print(pd.read_sql("SELECT COUNT(*) AS count FROM property_attributes", engine))
print(pd.read_sql("SELECT COUNT(*) AS count FROM sales", engine))
print(pd.read_sql("SELECT COUNT(*) AS count FROM buyers", engine))

   count
0     50
   count
0  21200
   count
0  21200
   count
0    720
   count
0  20000

In [32]:
query = "SELECT * FROM listings LIMIT 5"
pd.read_sql(query, engine)

,listing_id,city,property_type,price,sqft,date_listed,agent_id,latitude,longitude
0,L00001,New York,Apartment,1655144.01,2753.01,2023-05-06,A0015,33.965208,-69.861589
1,L00002,Los Angeles,Apartment,1519141.00,4966.99,2023-02-14,A0038,42.547892,-90.277860
2,L00003,Houston,Apartment,162489.00,1267.00,2023-04-22,A0015,28.732327,-115.952982
3,L00004,Phoenix,Apartment,1277015.98,2128.01,2024-01-02,A0042,26.403938,-74.771490
4,L00005,Phoenix,Townhouse,562297.01,4179.00,2023-10-29,A0018,39.425252,-83.917878

In [33]:
query = """
SELECT l.listing_id, l.city, l.property_type, l.price, a.name AS agent_name
FROM listings l
JOIN agents a
ON l.agent_id = a.agent_id
LIMIT 5
"""
pd.read_sql(query, engine)

  listing_id         city property_type       price   agent_name
0     L00001     New York     Apartment  1655144.01  Agent A0015
1     L00002  Los Angeles     Apartment  1519141.00  Agent A0038
2     L00003      Houston     Apartment   162489.00  Agent A0015
3     L00004      Phoenix     Apartment  1277015.98  Agent A0042
4     L00005      Phoenix     Townhouse   562297.01  Agent A0018

In [34]:
query = """
SELECT l.listing_id, l.city, l.property_type, l.price,
       p.bedrooms, p.bathrooms, p.furnishing_status
FROM listings l
JOIN property_attributes p
ON l.listing_id = p.listing_id
LIMIT 5
"""
pd.read_sql(query, engine)

,listing_id,city,property_type,price,bedrooms,bathrooms,furnishing_status
0,L00001,New York,Apartment,1655144.01,5,3,Furnished
1,L00002,Los Angeles,Apartment,1519141.00,2,2,Unfurnished
2,L00003,Houston,Apartment,162489.00,2,3,Semi-Furnished
3,L00004,Phoenix,Apartment,1277015.98,3,3,Furnished
4,L00005,Phoenix,Townhouse,562297.01,2,2,Semi-Furnished

In [35]:
query = """
SELECT city, ROUND(AVG(price), 2) AS avg_listing_price
FROM listings
GROUP BY city
ORDER BY avg_listing_price DESC
"""
pd.read_sql(query, engine)

          city  avg_listing_price
0     New York         2493319.74
1      Phoenix         2459961.76
2  Los Angeles         2442418.31
3      Houston         2436811.00
4      Chicago         2430677.90

In [ ]:
#1. Average listing price by city

In [36]:
query1 = """
SELECT city, ROUND(AVG(price), 2) AS avg_listing_price
FROM listings
GROUP BY city
ORDER BY avg_listing_price DESC;
"""
pd.read_sql(query1, engine)

          city  avg_listing_price
0     New York         2493319.74
1      Phoenix         2459961.76
2  Los Angeles         2442418.31
3      Houston         2436811.00
4      Chicago         2430677.90

In [ ]:
#2. Average price per square foot by property type

In [37]:
query2 = """
SELECT property_type,
       ROUND(AVG(price / sqft), 2) AS avg_price_per_sqft
FROM listings
GROUP BY property_type
ORDER BY avg_price_per_sqft DESC;
"""
pd.read_sql(query2, engine)

  property_type  avg_price_per_sqft
0         House              796.04
1     Apartment              792.20
2     Townhouse              789.75
3         Condo              754.68

In [ ]:
#3. Furnishing status impact on price

In [38]:
query3 = """
SELECT p.furnishing_status,
       ROUND(AVG(l.price), 2) AS avg_price
FROM listings l
JOIN property_attributes p
ON l.listing_id = p.listing_id
GROUP BY p.furnishing_status
ORDER BY avg_price DESC;
"""
pd.read_sql(query3, engine)

  furnishing_status   avg_price
0         Furnished  2463539.06
1    Semi-Furnished  2461192.65
2       Unfurnished  2433975.10

In [ ]:
#4. Average days on market by city

In [39]:
query4 = """
SELECT l.city,
       ROUND(AVG(s.days_on_market), 2) AS avg_days_on_market
FROM listings l
JOIN sales s
ON l.listing_id = s.listing_id
GROUP BY l.city
ORDER BY avg_days_on_market DESC;
"""
pd.read_sql(query4, engine)

          city  avg_days_on_market
0  Los Angeles               65.13
1      Chicago               64.25
2     New York               60.85
3      Phoenix               59.65
4      Houston               58.51

In [ ]:
#5. Top agents by total sales revenue

In [40]:
query5 = """
SELECT a.name,
       ROUND(SUM(s.sale_price), 2) AS total_sales_revenue
FROM agents a
JOIN listings l
ON a.agent_id = l.agent_id
JOIN sales s
ON l.listing_id = s.listing_id
GROUP BY a.name
ORDER BY total_sales_revenue DESC
LIMIT 10;
"""
pd.read_sql(query5, engine)

          name  total_sales_revenue
0  Agent A0011          27882272.01
1  Agent A0042          27191605.99
2  Agent A0043          24102418.01
3  Agent A0035          22725751.98
4  Agent A0014          22034008.02
5  Agent A0046          21335804.97
6  Agent A0048          21186305.99
7  Agent A0027          21099696.97
8  Agent A0009          20279274.94
9  Agent A0029          19586498.01

In [ ]:
#6. Unsold properties

In [41]:
query6 = """
SELECT l.listing_id, l.city, l.property_type, l.price, l.date_listed
FROM listings l
LEFT JOIN sales s
ON l.listing_id = s.listing_id
WHERE s.listing_id IS NULL;
"""
pd.read_sql(query6, engine)

      listing_id         city property_type       price date_listed
0         L00002  Los Angeles     Apartment  1519141.00  2023-02-14
1         L00005      Phoenix     Townhouse   562297.01  2023-10-29
2         L00009     New York     Townhouse  1224551.00  2024-05-13
3         L00014      Chicago     Apartment  1377440.01  2023-10-01
4         L00015  Los Angeles         House  1069428.99  2023-05-19
...          ...          ...           ...         ...         ...
20475     L21196      Phoenix         House   709355.28  2023-12-31
20476     L21197      Phoenix         Condo  3288420.13  2023-07-23
20477     L21198  Los Angeles     Apartment  1667441.24  2024-06-30
20478     L21199  Los Angeles     Townhouse  1648411.61  2023-09-17
20479     L21200     New York     Apartment  4991528.39  2023-07-28

[20480 rows x 5 columns]

In [ ]:
# 7.Percentage of properties sold above listing price

In [42]:
query7 = """
SELECT 
    ROUND(
        100.0 * SUM(CASE WHEN s.sale_price > l.price THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS percent_sold_above_listing
FROM listings l
JOIN sales s
ON l.listing_id = s.listing_id;
"""
pd.read_sql(query7, engine)

   percent_sold_above_listing
0                       49.31

In [ ]:
# 8. Sale-to-list price ratio by city

In [43]:
query8 = """
SELECT l.city,
       ROUND(AVG(s.sale_price / l.price), 2) AS sale_to_list_ratio
FROM listings l
JOIN sales s
ON l.listing_id = s.listing_id
GROUP BY l.city
ORDER BY sale_to_list_ratio DESC;
"""
pd.read_sql(query8, engine)

          city  sale_to_list_ratio
0      Chicago                 1.0
1     New York                 1.0
2  Los Angeles                 1.0
3      Houston                 1.0
4      Phoenix                 1.0

In [ ]:
#9. Rented vs non-rented property pricing

In [44]:
query9 = """
SELECT p.is_rented,
       ROUND(AVG(l.price), 2) AS avg_price
FROM listings l
JOIN property_attributes p
ON l.listing_id = p.listing_id
GROUP BY p.is_rented
ORDER BY avg_price DESC;
"""
pd.read_sql(query9, engine)

   is_rented  avg_price
0       True  2457184.9
1      False  2448250.3

In [ ]:
#10. Buyer type percentage

In [45]:
query10 = """
SELECT buyer_type,
       ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS percentage
FROM buyers
GROUP BY buyer_type
ORDER BY percentage DESC;
"""
pd.read_sql(query10, engine)

  buyer_type  percentage
0   End User        50.1
1   Investor        49.9

In [ ]:
#11. Most common payment mode

In [46]:
query11 = """
SELECT payment_mode,
       COUNT(*) AS total_transactions
FROM buyers
GROUP BY payment_mode
ORDER BY total_transactions DESC;
"""
pd.read_sql(query11, engine)

    payment_mode  total_transactions
0           Cash                5088
1            UPI                5012
2         Cheque                4951
3  Bank Transfer                4949

In [ ]:
#12. Average loan amount by buyer type

In [47]:
query12 = """
SELECT buyer_type,
       ROUND(AVG(loan_amount), 2) AS avg_loan_amount
FROM buyers
WHERE loan_taken = TRUE
GROUP BY buyer_type
ORDER BY avg_loan_amount DESC;
"""
pd.read_sql(query12, engine)

  buyer_type  avg_loan_amount
0   Investor       5211545.97
1   End User       5210307.45

In [ ]:
#13. Top agents by number of sales

In [48]:
query13 = """
SELECT a.name,
       COUNT(s.listing_id) AS total_sales
FROM agents a
JOIN listings l
ON a.agent_id = l.agent_id
JOIN sales s
ON l.listing_id = s.listing_id
GROUP BY a.name
ORDER BY total_sales DESC
LIMIT 10;
"""
pd.read_sql(query13, engine)

          name  total_sales
0  Agent A0042           25
1  Agent A0011           24
2  Agent A0014           21
3  Agent A0035           21
4  Agent A0046           20
5  Agent A0043           20
6  Agent A0048           19
7  Agent A0007           19
8  Agent A0029           18
9  Agent A0027           18

In [ ]:
#14. Properties with parking and power backup vs average price

In [49]:
query14 = """
SELECT p.parking_available,
       p.power_backup,
       ROUND(AVG(l.price), 2) AS avg_price
FROM listings l
JOIN property_attributes p
ON l.listing_id = p.listing_id
GROUP BY p.parking_available, p.power_backup
ORDER BY avg_price DESC;
"""
pd.read_sql(query14, engine)

   parking_available  power_backup   avg_price
0               True          True  2465651.62
1               True         False  2462363.80
2              False          True  2446292.59
3              False         False  2436677.75

In [ ]:
#15. Monthly sales trend

In [50]:
query15 = """
SELECT DATE_TRUNC('month', date_sold) AS sale_month,
       COUNT(*) AS total_sales,
       ROUND(SUM(sale_price), 2) AS total_sales_value
FROM sales
GROUP BY sale_month
ORDER BY sale_month;
"""
pd.read_sql(query15, engine)

                  sale_month  total_sales  total_sales_value
0  2022-12-31 18:30:00+00:00            7         5298400.96
1  2023-01-31 18:30:00+00:00           17        15945070.02
2  2023-02-28 18:30:00+00:00           20        19995066.06
3  2023-03-31 18:30:00+00:00           36        44208249.99
4  2023-04-30 18:30:00+00:00           45        51385673.97
5  2023-05-31 18:30:00+00:00           31        29643443.03
6  2023-06-30 18:30:00+00:00           48        56000209.96
7  2023-07-31 18:30:00+00:00           50        55050662.07
8  2023-08-31 18:30:00+00:00           46        49868704.96
9  2023-09-30 18:30:00+00:00           64        70202528.99
10 2023-10-31 18:30:00+00:00           46        49971190.03
11 2023-11-30 18:30:00+00:00           42        45793714.92
12 2023-12-31 18:30:00+00:00           44        48009108.08
13 2024-01-31 18:30:00+00:00           44        49637495.89
14 2024-02-29 18:30:00+00:00           39        41399120.01
15 2024-03-31 18:30:00+00:00           29        30068736.97
16 2024-04-30 18:30:00+00:00           45        45187319.00
17 2024-05-31 18:30:00+00:00           29        29498396.15
18 2024-06-30 18:30:00+00:00           24        25617081.97
19 2024-07-31 18:30:00+00:00           13        12823582.05
20 2024-08-31 18:30:00+00:00            1          229304.01

In [ ]:
#16. Do properties closer to metro stations command higher prices?

In [51]:
query16 = """
SELECT 
    CASE
        WHEN p.metro_distance_km <= 2 THEN '0-2 km'
        WHEN p.metro_distance_km <= 5 THEN '2-5 km'
        WHEN p.metro_distance_km <= 10 THEN '5-10 km'
        ELSE '10+ km'
    END AS metro_distance_bucket,
    ROUND(AVG(l.price), 2) AS avg_price
FROM listings l
JOIN property_attributes p
ON l.listing_id = p.listing_id
GROUP BY metro_distance_bucket
ORDER BY avg_price DESC;
"""
pd.read_sql(query16, engine)

  metro_distance_bucket   avg_price
0                10+ km  2527728.94
1               5-10 km  2442976.85
2                2-5 km  2404817.73
3                0-2 km  2377825.06

In [ ]:
# 17. How do bedrooms and bathrooms affect pricing?

In [52]:
query17 = """
SELECT p.bedrooms,
       p.bathrooms,
       ROUND(AVG(l.price), 2) AS avg_price
FROM listings l
JOIN property_attributes p
ON l.listing_id = p.listing_id
GROUP BY p.bedrooms, p.bathrooms
ORDER BY avg_price DESC;
"""
pd.read_sql(query17, engine)

    bedrooms  bathrooms   avg_price
0          2          4  2555766.23
1          5          4  2527191.97
2          1          2  2509474.77
3          2          3  2482618.93
4          3          4  2478881.22
5          5          2  2478068.17
6          4          4  2471535.90
7          1          3  2459032.59
8          2          1  2455735.36
9          1          4  2455532.96
10         3          3  2455024.25
11         4          2  2450749.99
12         4          1  2434956.38
13         1          1  2434001.41
14         3          1  2426007.97
15         5          3  2424066.83
16         3          2  2409122.73
17         4          3  2393515.03
18         5          1  2384940.47
19         2          2  2378687.66

In [ ]:
#18. How does year built influence listing price?

In [53]:
query18 = """
SELECT p.year_built,
       ROUND(AVG(l.price), 2) AS avg_price
FROM listings l
JOIN property_attributes p
ON l.listing_id = p.listing_id
GROUP BY p.year_built
ORDER BY p.year_built;
"""
pd.read_sql(query18, engine)

    year_built   avg_price
0         1990  2533791.60
1         1991  2573916.58
2         1992  2594651.56
3         1993  2611748.25
4         1994  2571504.92
5         1995  2434727.72
6         1996  2391385.75
7         1997  2493105.20
8         1998  2398158.87
9         1999  2498402.48
10        2000  2436148.36
11        2001  2438764.29
12        2002  2433615.48
13        2003  2395754.95
14        2004  2410642.66
15        2005  2518303.24
16        2006  2464741.47
17        2007  2379428.80
18        2008  2471225.25
19        2009  2401619.13
20        2010  2401119.97
21        2011  2440249.43
22        2012  2302495.50
23        2013  2348081.45
24        2014  2358476.99
25        2015  2457272.07
26        2016  2428168.81
27        2017  2393633.46
28        2018  2385864.55
29        2019  2561310.32
30        2020  2465414.49
31        2021  2545272.16
32        2022  2397386.65
33        2023  2500120.42

In [ ]:
#19. Which cities have the highest median property prices?

In [54]:
query19 = """
SELECT city,
       ROUND(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY price)::numeric, 2) AS median_price
FROM listings
GROUP BY city
ORDER BY median_price DESC;
"""
pd.read_sql(query19, engine)

          city  median_price
0     New York    2446518.63
1      Phoenix    2397597.97
2  Los Angeles    2380929.35
3      Chicago    2351084.47
4      Houston    2347582.06

In [ ]:
#20.How are properties distributed across price buckets?

In [55]:
query20 = """
SELECT 
    CASE
        WHEN price < 200000 THEN 'Below 200K'
        WHEN price < 500000 THEN '200K - 500K'
        WHEN price < 1000000 THEN '500K - 1M'
        ELSE 'Above 1M'
    END AS price_bucket,
    COUNT(*) AS property_count
FROM listings
GROUP BY price_bucket
ORDER BY property_count DESC;
"""
pd.read_sql(query20, engine)

  price_bucket  property_count
0     Above 1M           16931
1    500K - 1M            2402
2  200K - 500K            1426
3   Below 200K             441

In [ ]:
#21.Which property types sell the fastest?

In [56]:
query21 = """
SELECT l.property_type,
       ROUND(AVG(s.days_on_market), 2) AS avg_days_on_market
FROM listings l
JOIN sales s
ON l.listing_id = s.listing_id
GROUP BY l.property_type
ORDER BY avg_days_on_market ASC;
"""
pd.read_sql(query21, engine)

  property_type  avg_days_on_market
0         House               58.34
1     Apartment               60.65
2     Townhouse               60.96
3         Condo               66.54

In [ ]:
#22.Which listings took more than 90 days to sell?

In [57]:
query22 = """
SELECT l.listing_id,
       l.city,
       l.property_type,
       s.sale_price,
       s.days_on_market
FROM listings l
JOIN sales s
ON l.listing_id = s.listing_id
WHERE s.days_on_market > 90
ORDER BY s.days_on_market DESC;
"""
pd.read_sql(query22, engine)

    listing_id         city property_type  sale_price  days_on_market
0       L00157      Phoenix     Townhouse   707140.98          120.02
1       L00179      Chicago         Condo  1017871.01          120.01
2       L00259      Phoenix     Apartment  1577127.00          120.01
3       L00067      Chicago     Apartment   286681.00          119.99
4       L00287      Houston     Townhouse  1769308.00          119.97
..         ...          ...           ...         ...             ...
184     L00071      Chicago         House   985345.00           91.00
185     L00452  Los Angeles         House   994884.00           91.00
186     L00045  Los Angeles         House   480963.00           90.99
187     L00812      Houston         House   383243.01           90.99
188     L00568      Chicago         House  1644590.00           90.01

[189 rows x 5 columns]

In [ ]:
#23.How does metro distance affect time on market?

In [58]:
query23 = """
SELECT 
    CASE
        WHEN p.metro_distance_km <= 2 THEN '0-2 km'
        WHEN p.metro_distance_km <= 5 THEN '2-5 km'
        WHEN p.metro_distance_km <= 10 THEN '5-10 km'
        ELSE '10+ km'
    END AS metro_distance_bucket,
    ROUND(AVG(s.days_on_market), 2) AS avg_days_on_market
FROM property_attributes p
JOIN sales s
ON p.listing_id = s.listing_id
GROUP BY metro_distance_bucket
ORDER BY avg_days_on_market;
"""
pd.read_sql(query23, engine)

  metro_distance_bucket  avg_days_on_market
0               5-10 km               60.67
1                2-5 km               60.94
2                0-2 km               64.75

In [ ]:
#24.Which agents close deals fastest?

In [59]:
query24 = """
SELECT a.name,
       ROUND(AVG(s.days_on_market), 2) AS avg_closing_time
FROM agents a
JOIN listings l
ON a.agent_id = l.agent_id
JOIN sales s
ON l.listing_id = s.listing_id
GROUP BY a.name
ORDER BY avg_closing_time ASC
LIMIT 10;
"""
pd.read_sql(query24, engine)

          name  avg_closing_time
0  Agent A0044             36.88
1  Agent A0013             42.43
2  Agent A0037             44.50
3  Agent A0002             45.51
4  Agent A0008             46.64
5  Agent A0017             48.57
6  Agent A0026             49.50
7  Agent A0012             50.64
8  Agent A0010             51.13
9  Agent A0043             52.35

In [ ]:
#25.Does experience correlate with deals closed?

In [60]:
query25 = """
SELECT experience_years,
       ROUND(AVG(deals_closed), 2) AS avg_deals_closed
FROM agents
GROUP BY experience_years
ORDER BY experience_years;
"""
pd.read_sql(query25, engine)

    experience_years  avg_deals_closed
0                  1            262.00
1                  2             50.00
2                  3             14.00
3                  4            140.00
4                  5             88.33
5                  7             73.00
6                  9            283.00
7                 10             93.50
8                 11            109.00
9                 12            257.00
10                13            194.33
11                14             72.00
12                15            123.00
13                16             94.50
14                17            258.50
15                18            107.33
16                19            112.50
17                20            138.00
18                21            217.80
19                22             98.00
20                23            165.00
21                25             73.50

In [ ]:
#26.Do agents with higher ratings close deals faster?

In [61]:
query26 = """
SELECT rating,
       ROUND(AVG(avg_closing_days), 2) AS avg_closing_days
FROM agents
GROUP BY rating
ORDER BY rating DESC;
"""
pd.read_sql(query26, engine)

    rating  avg_closing_days
0      5.0             53.50
1      4.9             54.50
2      4.8             51.00
3      4.6             36.00
4      4.5             61.00
5      4.4             38.00
6      4.3             58.80
7      4.2             26.00
8      4.1             55.83
9      4.0             27.00
10     3.8             75.00
11     3.7             77.00
12     3.6             56.40
13     3.5             75.33
14     3.4             60.67
15     3.3             55.00
16     3.2             59.75
17     3.1             50.00

In [ ]:
#27.What is the average commission earned by each agent?

In [62]:
query27 = """
SELECT a.name,
       ROUND(AVG(s.sale_price * a.commission_rate / 100), 2) AS avg_commission_earned
FROM agents a
JOIN listings l
ON a.agent_id = l.agent_id
JOIN sales s
ON l.listing_id = s.listing_id
GROUP BY a.name
ORDER BY avg_commission_earned DESC;
"""
pd.read_sql(query27, engine)

           name  avg_commission_earned
0   Agent A0009               33997.61
1   Agent A0002               32326.16
2   Agent A0035               32032.49
3   Agent A0012               31737.61
4   Agent A0030               31665.09
5   Agent A0018               31438.36
6   Agent A0031               30358.05
7   Agent A0050               28564.40
8   Agent A0017               28406.74
9   Agent A0024               27805.90
10  Agent A0003               27760.70
11  Agent A0019               27556.30
12  Agent A0032               27379.03
13  Agent A0029               26659.40
14  Agent A0021               26574.64
15  Agent A0020               25646.69
16  Agent A0034               24640.04
17  Agent A0042               24363.68
18  Agent A0001               24231.89
19  Agent A0049               23723.41
20  Agent A0011               23351.40
21  Agent A0013               23176.67
22  Agent A0023               23049.93
23  Agent A0045               22728.98
24  Agent A0033               22723.44
25  Agent A0027               22506.34
26  Agent A0025               22250.22
27  Agent A0028               22121.75
28  Agent A0043               21089.62
29  Agent A0036               20770.32
30  Agent A0014               20670.00
31  Agent A0010               20298.85
32  Agent A0004               19364.05
33  Agent A0044               18573.68
34  Agent A0037               18267.24
35  Agent A0006               17404.47
36  Agent A0008               17312.42
37  Agent A0007               17251.46
38  Agent A0046               16748.61
39  Agent A0015               16532.35
40  Agent A0039               16459.71
41  Agent A0047               15692.45
42  Agent A0048               14941.92
43  Agent A0040               14632.37
44  Agent A0022               13587.76
45  Agent A0016               13002.01
46  Agent A0041               12388.18
47  Agent A0026               11518.01
48  Agent A0038               11244.98
49  Agent A0005               11226.97

In [ ]:
#28.Which agents currently have the most active listings?

In [63]:
query28 = """
SELECT a.name,
       COUNT(l.listing_id) AS active_listings
FROM agents a
JOIN listings l
ON a.agent_id = l.agent_id
LEFT JOIN sales s
ON l.listing_id = s.listing_id
WHERE s.listing_id IS NULL
GROUP BY a.name
ORDER BY active_listings DESC
LIMIT 10;
"""
pd.read_sql(query28, engine)

          name  active_listings
0  Agent A0023              446
1  Agent A0011              439
2  Agent A0008              438
3  Agent A0042              435
4  Agent A0014              432
5  Agent A0044              430
6  Agent A0020              426
7  Agent A0048              425
8  Agent A0015              425
9  Agent A0012              425

In [ ]:
#29.Which cities have the highest loan uptake rate?

In [64]:
query29 = """
SELECT l.city,
       ROUND(
           100.0 * SUM(CASE WHEN b.loan_taken = TRUE THEN 1 ELSE 0 END) / COUNT(*),
           2
       ) AS loan_uptake_rate
FROM buyers b
JOIN sales s
ON b.sale_id = s.listing_id
JOIN listings l
ON s.listing_id = l.listing_id
GROUP BY l.city
ORDER BY loan_uptake_rate DESC;
"""
pd.read_sql(query29, engine)

          city  loan_uptake_rate
0  Los Angeles             50.99
1      Chicago             50.57
2     New York             50.22
3      Houston             49.71
4      Phoenix             49.50

In [ ]:
#30.Do loan-backed purchases take longer to close?

In [65]:
query30 = """
SELECT b.loan_taken,
       ROUND(AVG(s.days_on_market), 2) AS avg_days_on_market
FROM buyers b
JOIN sales s
ON b.sale_id = s.listing_id
GROUP BY b.loan_taken
ORDER BY avg_days_on_market DESC;
"""
pd.read_sql(query30, engine)

   loan_taken  avg_days_on_market
0        True               62.15
1       False               61.07

In [ ]:
#All 30 SQL queries completed